### ISSUE TITLE
快速教程不正确、不完整

### ISSUE THREAD

**Issue by tzu2020** [neugates/neuron-docs#25]
File: [/zh_CN/README.md](https://docs.emqx.cn/neuron/latest/) 我照着neron快速教程无法走完一个测试用例，希望开发者能提供一个准确完整的教程

**Comment by lixiumei123** [comment]
是连接不上模拟器，还是什么其他问题？模拟器所在的Windows的防火墙如果不关闭可能会导致Neuron连接不上模拟器。

**Comment by joey8869** [comment]
Neuron1.4.0官网更新了
